version: '3'
services:

    php:
        build:
            context: ./docker/php
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - .:/var/www

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./public:/var/www/public:cached
